import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!;
const BOT_TOKEN=Deno.env.get('TELEGRAM_BOT_TOKEN')!;
const BOT_USERNAME=(Deno.env.get('TELEGRAM_BOT_USERNAME')||'Astshara_app_bot').replace(/^@/,'');
const WEBHOOK_SECRET=Deno.env.get('TELEGRAM_WEBHOOK_SECRET')||'';
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{autoRefreshToken:false,persistSession:false}});
const authClient=createClient(SUPABASE_URL,ANON_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const normalizeDigits=(v:string)=>String(v||'').replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c)));
const normalizePhone=(v:string)=>{let p=normalizeDigits(v).trim().replace(/\s+/g,'').replace(/[()\-]/g,'').replace(/[^0-9+]/g,'');if(p.startsWith('+'))p=p.slice(1);if(p.startsWith('00'))p=p.slice(2);if(p.startsWith('0'))p=`964${p.slice(1)}`;if(!p.startsWith('964'))p=`964${p}`;return p};
const phoneCandidates=(p:string)=>[p,`0${p.slice(3)}`,`+${p}`];
const normalizeCode=(v:string)=>normalizeDigits(v).replace(/\s/g,'');
const sha256=async(t:string)=>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')};
const randomPassword=()=>crypto.randomUUID()+crypto.randomUUID();
const syntheticEmail=(p:string)=>`telegram.${p}@login.astshara.app`;
const LINKED='هذا الحساب مرتبط بحساب آخر في تطبيق استشارة.';
async function telegram(m:string,b:Record<string,unknown>){const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${m}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(!d.ok)throw new Error(d.description||`Telegram ${m} failed`);return d.result}
async function ensureWebhook(){if(!WEBHOOK_SECRET)throw new Error('إعداد أمان Telegram غير مكتمل');const body:Record<string,unknown>={url:`${SUPABASE_URL}/functions/v1/telegram-auth-v2?webhook=1`,allowed_updates:['message'],drop_pending_updates:false,secret_token:WEBHOOK_SECRET};await telegram('setWebhook',body)}
async function findProfile(p:string){const{data,error}=await admin.from('profiles').select('*').in('phone',phoneCandidates(p)).limit(1).maybeSingle();if(error)throw new Error(`تعذر التحقق من الرقم: ${error.message}`);return data}
async function findProfileById(id:string){if(!id)return null;const{data,error}=await admin.from('profiles').select('*').eq('id',id).maybeSingle();if(error)throw new Error(`تعذر استرجاع الحساب المرتبط: ${error.message}`);return data}
async function findProfileByAuthId(id:string){if(!id)return null;const{data,error}=await admin.from('profiles').select('*').eq('auth_id',id).maybeSingle();if(error)throw new Error(`تعذر استرجاع الملف الشخصي: ${error.message}`);return data}
async function findTelegramProfile(id:number){const{data,error}=await admin.from('profiles').select('*').eq('telegram_user_id',id).limit(1).maybeSingle();if(error)throw new Error(`تعذر التحقق من حساب Telegram: ${error.message}`);return data}
async function finishCreatedProfile(authId:string,r:any,fullName:string,role:string,email:string){const p=await findProfileByAuthId(authId);if(!p)throw new Error('تم إنشاء الحساب لكن تعذر استرجاع الملف الشخصي.');const{error}=await admin.from('profiles').update({phone:r.phone,email,full_name:fullName,role:role==='lawyer'?'lawyer':'user',telegram_user_id:r.telegram_user_id,updated_at:new Date().toISOString()}).eq('id',p.id).eq('auth_id',authId);if(error)throw new Error(`تعذر إكمال ملف المستخدم: ${error.message}`);return await findProfileByAuthId(authId)}
async function enforceStartRateLimit(phone:string){const since=new Date(Date.now()-600000).toISOString();const{count,error}=await admin.from('telegram_login_requests').select('id',{count:'exact',head:true}).eq('phone',phone).gte('created_at',since);if(error)throw new Error(`تعذر التحقق من عدد المحاولات: ${error.message}`);if((count??0)>=5)throw new Error('تم تجاوز عدد محاولات Telegram المسموح بها. حاول لاحقاً.')}
async function start(phoneRaw:string,mode='login',fullName?:string,role?:string){const phone=normalizePhone(phoneRaw);if(!/^9647\d{9}$/.test(phone))throw new Error('رقم الهاتف العراقي غير صحيح');const signup=mode==='signup';if(signup){if(!fullName||fullName.trim().length<3)throw new Error('الاسم الكامل مطلوب');if(role!=='user'&&role!=='lawyer')throw new Error('نوع الحساب غير صحيح');if(await findProfile(phone))throw new Error('هذا الرقم مرتبط بحساب آخر. يرجى استخدام رقم هاتف آخر أو تسجيل الدخول بالحساب المرتبط به.')}await enforceStartRateLimit(phone);await ensureWebhook();const token=crypto.randomUUID();await admin.from('telegram_login_requests').update({status:'expired'}).eq('phone',phone).in('status',['waiting','code_sent','telegram_verified']).is('session_claimed_at',null);const{error}=await admin.from('telegram_login_requests').insert({request_token:token,phone,status:'waiting',attempts:0,expires_at:new Date(Date.now()+600000).toISOString(),mode:signup?'signup':'login',full_name:signup?fullName!.trim():null,role:signup?role:null});if(error)throw new Error(`تعذر إنشاء طلب Telegram: ${error.message}`);return{ok:true,request_token:token,telegram_url:`https://t.me/${BOT_USERNAME}?start=${token}`}}
async function webhook(req:Request){if(!WEBHOOK_SECRET)return json({ok:false,error:'Telegram webhook security is not configured'},503);if(req.headers.get('x-telegram-bot-api-secret-token')!==WEBHOOK_SECRET)return json({ok:false},401);const u=await req.json(),m=u?.message;if(!m?.chat?.id)return json({ok:true});if(m.contact){await handleContact(m);return json({ok:true})}const id=Number(m.chat.id),text=String(m.text||'').trim(),arg=text.match(/^\/start(?:\s+(.+))?$/i)?.[1]?.trim();if(!arg){await telegram('sendMessage',{chat_id:id,text:'مرحباً بك في بوت استشارة ⚖️\nافتح رابط تسجيل الدخول من تطبيق استشارة واضغط «بدء». ثم اختر «مشاركة رقم الهاتف» لإكمال الدخول تلقائياً.'});return json({ok:true})}const{data:r,error}=await admin.from('telegram_login_requests').select('*').eq('request_token',arg).maybeSingle();if(error||!r||new Date(r.expires_at).getTime()<=Date.now()||r.status==='expired'||r.session_claimed_at){await telegram('sendMessage',{chat_id:id,text:'انتهت صلاحية طلب التحقق أو تم استخدامه مسبقاً. ارجع إلى تطبيق استشارة واطلب محاولة جديدة.'});return json({ok:true})}await admin.from('telegram_login_requests').update({telegram_user_id:id,telegram_username:m.from?.username??null,telegram_first_name:m.from?.first_name??null,telegram_last_name:m.from?.last_name??null}).eq('id',r.id).eq('status','waiting').is('session_claimed_at',null);await telegram('sendMessage',{chat_id:id,text:'لإكمال تسجيل الدخول تلقائياً، اضغط الزر أدناه لمشاركة رقم هاتفك مع بوت استشارة. لن يتم استخدامه إلا للتحقق من ملكية الرقم.',reply_markup:{keyboard:[[{text:'مشاركة رقم الهاتف',request_contact:true}]],resize_keyboard:true,one_time_keyboard:true}});return json({ok:true})}
async function handleContact(m:any){const id=Number(m.chat.id),contact=m.contact;if(!contact?.phone_number)return false;const contactPhone=normalizePhone(String(contact.phone_number));let{data:r,error}=await admin.from('telegram_login_requests').select('*').eq('telegram_user_id',id).eq('status','waiting').is('session_claimed_at',null).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(`تعذر العثور على طلب Telegram: ${error.message}`);if(!r){const fallback=await admin.from('telegram_login_requests').select('*').in('phone',phoneCandidates(contactPhone)).eq('status','waiting').is('session_claimed_at',null).order('created_at',{ascending:false}).limit(1).maybeSingle();if(fallback.error)throw new Error(`تعذر العثور على طلب Telegram: ${fallback.error.message}`);r=fallback.data;}if(!r)return false;if(new Date(r.expires_at).getTime()<=Date.now()){await admin.from('telegram_login_requests').update({status:'expired'}).eq('id',r.id).eq('status','waiting');return false}if(contactPhone!==normalizePhone(r.phone)){await telegram('sendMessage',{chat_id:id,text:'رقم الهاتف الذي تمت مشاركته لا يطابق الرقم المدخل في استشارة. ارجع إلى التطبيق وتحقق من الرقم.',reply_markup:{remove_keyboard:true}});return true}const existingTelegram=await findTelegramProfile(id);if(existingTelegram){if(r.mode!=='login'||normalizePhone(existingTelegram.phone)!==contactPhone){await telegram('sendMessage',{chat_id:id,text:LINKED,reply_markup:{remove_keyboard:true}});return true}}const{error:bindingError}=await admin.from('telegram_login_requests').update({telegram_user_id:id,telegram_username:m.from?.username??null,telegram_first_name:m.from?.first_name??null,telegram_last_name:m.from?.last_name??null}).eq('id',r.id).eq('status','waiting').is('session_claimed_at',null);if(bindingError)throw new Error(`تعذر تثبيت طلب Telegram: ${bindingError.message}`);const profile=await findProfile(r.phone);if(r.mode==='login'&&!profile){await telegram('sendMessage',{chat_id:id,text:'لم يتم العثور على حساب بهذا الرقم. أنشئ حساباً أولاً من استشارة.',reply_markup:{remove_keyboard:true}});return true}if(r.mode==='signup'&&profile){await telegram('sendMessage',{chat_id:id,text:'هذا الرقم مرتبط بحساب موجود. استخدم تسجيل الدخول بدلاً من إنشاء حساب جديد.',reply_markup:{remove_keyboard:true}});return true}await admin.from('telegram_login_requests').update({status:'telegram_verified',verified_profile_id:profile?.id??null,verified_at:null,telegram_user_id:id,telegram_username:m.from?.username??null,telegram_first_name:m.from?.first_name??null,telegram_last_name:m.from?.last_name??null}).eq('id',r.id).eq('status','waiting').is('session_claimed_at',null);if(profile?.id)await admin.from('profiles').update({telegram_user_id:id,updated_at:new Date().toISOString()}).eq('id',profile.id);await telegram('sendMessage',{chat_id:id,text:'تم التحقق بنجاح. ارجع إلى استشارة، وسيتم إكمال العملية تلقائياً.',reply_markup:{remove_keyboard:true}});return true}
async function status(token:string){const{data:r,error}=await admin.from('telegram_login_requests').select('status,expires_at,telegram_user_id,mode,verified_profile_id,session_claimed_at').eq('request_token',token).maybeSingle();if(error)throw new Error(error.message);if(!r)throw new Error('طلب التحقق غير موجود');if(r.session_claimed_at)return{ok:false,status:'used',mode:r.mode,verified_profile_id:r.verified_profile_id??null};if(new Date(r.expires_at).getTime()<=Date.now()&&r.status!=='verified')return{ok:false,status:'expired'};return{ok:true,status:r.status,telegram_linked:!!r.telegram_user_id,mode:r.mode,verified_profile_id:r.verified_profile_id??null}}
async function claimSession(r:any){const{data,error}=await admin.rpc('claim_telegram_login_session',{p_request_id:r.id,p_telegram_user_id:Number(r.telegram_user_id)});if(error)throw new Error(`تعذر تثبيت طلب Telegram: ${error.message}`);if(data!==true)throw new Error('طلب Telegram تم استخدامه مسبقاً أو انتهت صلاحيته. ابدأ محاولة جديدة.');}
async function createSessionForProfile(r:any,p:any){if(!p?.auth_id)throw new Error('تعذر استرجاع الحساب المرتبط');const user=(await admin.auth.admin.getUserById(p.auth_id)).data.user;if(!user)throw new Error('تعذر استرجاع الحساب');const email=user.email||syntheticEmail(r.phone),password=randomPassword();const{error:ue}=await admin.auth.admin.updateUserById(user.id,{password,user_metadata:{...(user.user_metadata||{}),full_name:p.full_name,role:p.role}});if(ue)throw new Error(`تعذر تجهيز جلسة الدخول: ${ue.message}`);const{data:login,error:le}=await authClient.auth.signInWithPassword({email,password});if(le||!login.session)throw new Error(`تعذر إنشاء جلسة الدخول: ${le?.message||'الجلسة غير متاحة'}`);await admin.from('profiles').update({telegram_user_id:r.telegram_user_id,updated_at:new Date().toISOString()}).eq('id',p.id);await admin.from('telegram_login_requests').update({status:'verified',verified_at:new Date().toISOString(),verified_profile_id:p.id}).eq('id',r.id).eq('status','telegram_verified');return{ok:true,access_token:login.session.access_token,refresh_token:login.session.refresh_token,userId:user.id}}
async function verify(token:string,rawCode?:string){const{data:r,error}=await admin.from('telegram_login_requests').select('*').eq('request_token',token).maybeSingle();if(error)throw new Error(error.message);if(!r)throw new Error('طلب التحقق غير موجود');if(r.session_claimed_at)throw new Error('طلب Telegram تم استخدامه مسبقاً. ابدأ محاولة جديدة.');if(new Date(r.expires_at).getTime()<=Date.now()){await admin.from('telegram_login_requests').update({status:'expired'}).eq('id',r.id).eq('status','waiting').is('session_claimed_at',null);throw new Error('انتهت صلاحية رمز التحقق. اطلب محاولة جديدة')}
if(r.status==='telegram_verified'&&r.telegram_user_id){let p=null;if(r.verified_profile_id)p=await findProfileById(r.verified_profile_id);if(!p)p=await findProfile(r.phone);if(r.mode==='login'){if(!p)throw new Error('لم يتم العثور على حساب مرتبط بهذا الرقم. يرجى إنشاء حساب أولاً.');if(p.telegram_user_id&&Number(p.telegram_user_id)!==Number(r.telegram_user_id))throw new Error(LINKED);if(normalizePhone(p.phone)!==normalizePhone(r.phone))throw new Error('رقم الهاتف لا يطابق الحساب المرتبط.');await claimSession(r);return await createSessionForProfile(r,p)}if(r.mode==='signup'){if(p)throw new Error('هذا الرقم مرتبط بحساب آخر. يرجى استخدام رقم هاتف آخر أو تسجيل الدخول بالحساب المرتبط به.');const existingTelegram=await findTelegramProfile(Number(r.telegram_user_id));if(existingTelegram)throw new Error(LINKED);const email=syntheticEmail(r.phone),password=randomPassword(),role=r.role==='lawyer'?'lawyer':'user',fullName=String(r.full_name||'').trim();if(fullName.length<3)throw new Error('الاسم الكامل مطلوب');await claimSession(r);const{data:created,error:ce}=await admin.auth.admin.createUser({email,password,email_confirm:true,phone:`+${r.phone}`,phone_confirm:true,user_metadata:{full_name:fullName,role}});if(ce)throw new Error(/already|exists|registered|duplicate/i.test(ce.message)?LINKED:`تعذر إنشاء الحساب: ${ce.message}`);try{const newProfile=await finishCreatedProfile(created.user.id,r,fullName,role,email);if(!newProfile)throw new Error('تم إنشاء الحساب لكن تعذر استرجاع الملف الشخصي.');return await createSessionForProfile(r,newProfile)}catch(e){await admin.auth.admin.deleteUser(created.user.id);throw e}}}
const code=normalizeCode(rawCode||'');if(!r.telegram_user_id||r.status!=='code_sent')throw new Error('لم تصل إشارة Telegram بعد. افتح Telegram واضغط «بدء» من رابط استشارة، ثم انتظر وصول الرمز.');if(!/^\d{6}$/.test(code))throw new Error('رمز التحقق يجب أن يتكون من 6 أرقام');if((r.attempts??0)>=5)throw new Error('تم تجاوز عدد المحاولات المسموح بها. اطلب رمزاً جديداً');const expected=await sha256(`${code}:${token}`);if(expected!==r.code_hash){await admin.from('telegram_login_requests').update({attempts:(r.attempts??0)+1}).eq('id',r.id).eq('status','code_sent').is('session_claimed_at',null);throw new Error('رمز التحقق غير صحيح')}const phone=r.phone,mode=r.mode||'login',profile=await findProfile(phone),tp=await findTelegramProfile(Number(r.telegram_user_id));if(tp&&(!profile||tp.id!==profile.id||normalizePhone(tp.phone)!==normalizePhone(phone)))throw new Error(LINKED);if(mode==='signup'&&profile)throw new Error('هذا الرقم مرتبط بحساب آخر. يرجى استخدام رقم هاتف آخر أو تسجيل الدخول بالحساب المرتبط به.');if(mode==='login'&&!profile)throw new Error('لم يتم العثور على حساب مرتبط بهذا الرقم. يرجى إنشاء حساب أولاً.');let resolvedProfile=profile;if(!resolvedProfile){const email=syntheticEmail(phone),password=randomPassword(),role=r.role==='lawyer'?'lawyer':'user',fullName=String(r.full_name||'').trim();const{data:created,error:ce}=await admin.auth.admin.createUser({email,password,email_confirm:true,phone:`+${phone}`,phone_confirm:true,user_metadata:{full_name:fullName,role}});if(ce)throw new Error(/already|exists|registered|duplicate/i.test(ce.message)?LINKED:`تعذر إنشاء الحساب: ${ce.message}`);try{resolvedProfile=await finishCreatedProfile(created.user.id,r,fullName,role,email)}catch(e){await admin.auth.admin.deleteUser(created.user.id);throw e}}await claimSession(r);return await createSessionForProfile(r,resolvedProfile)}
Deno.serve(async req=>{try{if(req.method==='OPTIONS')return new Response('ok',{status:200,headers:cors});const url=new URL(req.url);if(url.searchParams.get('webhook')==='1')return await webhook(req);if(req.method!=='POST')return json({ok:false,error:'Method not allowed'},405);const b=await req.json();if(b.action==='start')return json(await start(b.phone,b.mode||'login',b.full_name,b.role));if(b.action==='status')return json(await status(b.request_token));if(b.action==='verify')return json(await verify(b.request_token,b.code));return json({ok:false,error:'إجراء غير معروف'},400)}catch(e){console.error('telegram-auth-v2 error',e instanceof Error?e.message:String(e));const m=e instanceof Error?e.message:String(e);const s=m===LINKED||/مرتبط بحساب آخر|هذا الرقم مرتبط/.test(m)?400:(/غير صحيح|غير موجود|انتهت|تجاوز|يجب أن|لم تصل إشارة|مطلوب|نوع الحساب|تم استخدامه مسبقاً/.test(m)?400:500);return json({ok:false,error:m},s)}});
