import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const first=(...v:any[])=>v.find(x=>x!==undefined&&x!==null&&x!=="");
const num=(v:any)=>{if(v===undefined||v===null||v==="")return null;const n=Number(String(v).replace(/,/g,""));return Number.isFinite(n)?n:null};
const statusOf=(d:any)=>String(first(d?.status,d?.data?.status,d?.result?.status,d?.payment?.status,d?.paymentStatus,d?.data?.paymentStatus,"")).trim().toUpperCase();
const amountOf=(d:any)=>num(first(d?.amount,d?.data?.amount,d?.result?.amount,d?.payment?.amount,d?.paymentAmount,d?.data?.paymentAmount));
const confirmedAmountOf=(d:any)=>num(first(d?.confirmedAmount,d?.data?.confirmedAmount,d?.result?.confirmedAmount,d?.payment?.confirmedAmount));
const currencyOf=(d:any)=>String(first(d?.currency,d?.data?.currency,d?.result?.currency,d?.payment?.currency,d?.paymentCurrency,d?.data?.paymentCurrency,"")).trim().toUpperCase();
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const auth=req.headers.get('Authorization');if(!auth)throw new Error('غير مصرح');
 const url=Deno.env.get('SUPABASE_URL')!,sr=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!;
 const base=(Deno.env.get('QICARD_API_URL')||Deno.env.get('QICARD_API_BASE_URL')||'https://uat-sandbox-3ds-api.qi.iq/api/v1').replace(/\/$/,'');
 const username=Deno.env.get('QICARD_USERNAME'),password=Deno.env.get('QICARD_PASSWORD'),terminal=Deno.env.get('QICARD_TERMINAL_ID');if(!username||!password||!terminal)throw new Error('بيانات بوابة كي كارد غير مكتملة');
 const client=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:ud,error:ae}=await client.auth.getUser();if(ae||!ud.user)throw new Error('المستخدم غير مسجل دخول');
 const {booking_id}=await req.json();if(!booking_id)throw new Error('معرّف الحجز مطلوب');const admin=createClient(url,sr);
 const {data:profile,error:profileError}=await admin.from('profiles').select('id').eq('auth_id',ud.user.id).maybeSingle();if(profileError)throw profileError;if(!profile)throw new Error('ملف المستخدم غير مكتمل');
 const {data:b,error:be}=await admin.from('bookings').select('id,user_id,status,lawyer_approved,price').eq('id',booking_id).maybeSingle();if(be)throw be;if(!b||b.user_id!==profile.id)throw new Error('لا تملك صلاحية هذا الحجز');
 const {data:ps,error:pe}=await admin.from('payments').select('id,booking_id,qicard_payment_id,qicard_request_id,status,created_at').eq('booking_id',booking_id).not('qicard_payment_id','is',null).order('created_at',{ascending:false});if(pe)throw pe;if(!ps?.length)throw new Error('لا توجد عملية كي كارد مرتبطة بهذا الحجز');
 const headers={Accept:'application/json',Authorization:`Basic ${btoa(`${username}:${password}`)}`,'X-Terminal-Id':terminal};const checks:any[]=[];let successPick:any=null,failedPick:any=null,pendingPick:any=null;
 for(const p of ps){try{const r=await fetch(`${base}/payment/${encodeURIComponent(p.qicard_payment_id)}/status`,{headers});const text=await r.text();let d:any=null;try{d=JSON.parse(text)}catch{}const raw=statusOf(d),amount=amountOf(d),confirmed=confirmedAmountOf(d),currency=currencyOf(d);const amountOk=amount===null||amount===Number(b.price),confirmedOk=confirmed===null||confirmed===Number(b.price),currencyOk=!currency||currency==='IQD';checks.push({payment_id:p.id,qicard_payment_id:p.qicard_payment_id,qicard_request_id:p.qicard_request_id,http_status:r.status,qicard_status:raw||null,amount,confirmed_amount:confirmed,currency:currency||null,validation:{amount_ok:amountOk,confirmed_amount_ok:confirmedOk,currency_ok:currencyOk},response_preview:text.slice(0,500)});console.log(JSON.stringify({event:'qicard_status_check',booking_id:booking_id,payment_id:p.id,qicard_payment_id:p.qicard_payment_id,request_id:p.qicard_request_id,http_status:r.status,qicard_status:raw||null,amount,confirmed_amount:confirmed,currency:currency||null,amount_ok:amountOk,confirmed_amount_ok:confirmedOk,currency_ok:currencyOk}));if(!r.ok||!d)continue;if(raw==='SUCCESS'&&amountOk&&confirmedOk&&currencyOk&&!successPick)successPick={p,d,raw};else if((raw==='FAILED'||raw==='AUTHENTICATION_FAILED')&&amountOk&&confirmedOk&&currencyOk&&!failedPick)failedPick={p,d,raw};else if(!pendingPick)pendingPick={p,d,raw};}catch(e){checks.push({payment_id:p.id,qicard_payment_id:p.qicard_payment_id,error:e instanceof Error?e.message:'request failed'});}}
 const chosen=successPick||failedPick||pendingPick;if(!chosen)return json({payment_status:'قيد معالجة الدفع',booking_status:b.status,checks});
 const {p,d,raw}=chosen,success=raw==='SUCCESS',failed=raw==='FAILED'||raw==='AUTHENTICATION_FAILED',now=new Date().toISOString(),details=first(d?.details,d?.data?.details,d?.payment?.details)||{};
 const mapped=success?'تم الدفع':failed?'فشل الدفع':'قيد معالجة الدفع';
 const {error:ue}=await admin.from('payments').update({status:mapped,qicard_raw_status:raw||null,qicard_payment_type:first(d?.paymentType,d?.data?.paymentType,d?.payment?.paymentType)??null,qicard_payment_system:details?.paymentSystem??null,qicard_rrn:details?.rrn??null,qicard_auth_id:details?.authId??null,qicard_updated_at:now,verified_at:success?now:null}).eq('id',p.id);if(ue)throw ue;
 let bookingStatus=b.status;if(success)bookingStatus=b.lawyer_approved?'مؤكد':'قيد مراجعة المحامي';else if(failed)bookingStatus='قيد انتظار الدفع';else bookingStatus='قيد معالجة الدفع';if(bookingStatus!==b.status){const {error}=await admin.from('bookings').update({status:bookingStatus}).eq('id',b.id);if(error)throw error;}
 return json({payment_status:mapped,qicard_status:raw||null,booking_status:bookingStatus,payment_id:p.id,qicard_payment_id:p.qicard_payment_id,qicard_request_id:p.qicard_request_id,checks});
 }catch(e){console.error('QiCard status error',e);return json({error:e instanceof Error?e.message:'حدث خطأ غير متوقع'},400)}});