revoke execute on function public.archive_booking_for_lawyer(uuid) from public, anon; grant execute on function public.archive_booking_for_lawyer(uuid) to authenticated;
revoke execute on function public.change_booking_status(uuid,text) from public; grant execute on function public.change_booking_status(uuid,text) to authenticated;
revoke execute on function public.change_custom_consultation_request_status(uuid,text) from public; grant execute on function public.change_custom_consultation_request_status(uuid,text) to authenticated;
revoke execute on function public.create_booking(uuid,timestamptz,text,text,text,text,text,uuid,text) from public, anon; grant execute on function public.create_booking(uuid,timestamptz,text,text,text,text,text,uuid,text) to authenticated;
revoke execute on function public.create_custom_consultation_request(uuid,text,text,text) from public; grant execute on function public.create_custom_consultation_request(uuid,text,text,text) to authenticated;
revoke execute on function public.get_booking_client_name(uuid) from public; grant execute on function public.get_booking_client_name(uuid) to authenticated;
revoke execute on function public.get_booking_contact(uuid) from public; grant execute on function public.get_booking_contact(uuid) to authenticated;
revoke execute on function public.get_booking_contact_info(uuid) from public, anon; grant execute on function public.get_booking_contact_info(uuid) to authenticated;
revoke execute on function public.get_booking_participant_contact_info(uuid) from public; grant execute on function public.get_booking_participant_contact_info(uuid) to authenticated;
revoke execute on function public.get_lawyer_custom_consultation_requests() from public; grant execute on function public.get_lawyer_custom_consultation_requests() to authenticated;
revoke execute on function public.get_my_role() from public, anon; grant execute on function public.get_my_role() to authenticated;
revoke execute on function public.get_profile_auth_id(uuid) from public, anon; grant execute on function public.get_profile_auth_id(uuid) to authenticated;
revoke execute on function public.get_public_lawyer(uuid) from public; grant execute on function public.get_public_lawyer(uuid) to anon, authenticated;
revoke execute on function public.get_public_lawyers() from public; grant execute on function public.get_public_lawyers() to anon, authenticated;
revoke execute on function public.is_admin() from public, anon; grant execute on function public.is_admin() to authenticated;
revoke execute on function public.record_manual_payment(uuid,numeric) from public; grant execute on function public.record_manual_payment(uuid,numeric) to authenticated;
revoke execute on function public.report_booking_no_show(uuid) from public, anon; grant execute on function public.report_booking_no_show(uuid) to authenticated;
revoke execute on function public.review_booking(uuid,boolean) from public, anon; grant execute on function public.review_booking(uuid,boolean) to authenticated;
revoke execute on function public.review_specialization_change(uuid,boolean,text) from public; grant execute on function public.review_specialization_change(uuid,boolean,text) to authenticated;
revoke execute on function public.submit_payment(uuid,text,text,text) from public; grant execute on function public.submit_payment(uuid,text,text,text) to authenticated;
revoke execute on function public.update_own_profile_contact(text,text,text,text) from public, anon; grant execute on function public.update_own_profile_contact(text,text,text,text) to authenticated;
revoke execute on function public.notify_booking_events() from public, anon, authenticated;
revoke execute on function public.notify_custom_request_events() from public, anon, authenticated;
revoke execute on function public.notify_lawyer_profile_events() from public, anon, authenticated;
revoke execute on function public.notify_message_event() from public, anon, authenticated;
revoke execute on function public.notify_payment_events() from public, anon, authenticated;
revoke execute on function public.notify_review_event() from public, anon, authenticated;
revoke execute on function public.notify_specialization_request_events() from public, anon, authenticated;
revoke execute on function public.enqueue_user_notification(uuid,text,text,text) from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.set_custom_request_updated_at() from public, anon, authenticated;
revoke execute on function public.sync_booking_from_payment() from public, anon, authenticated;
revoke execute on function public.sync_public_lawyer_directory() from public, anon, authenticated;
revoke execute on function public.track_completed_consultation() from public, anon, authenticated;
revoke execute on function public.update_conversation_last_message() from public, anon, authenticated;
revoke execute on function public.update_lawyer_rating() from public, anon, authenticated;
revoke execute on function public.validate_review() from public, anon, authenticated;
