-- Production-safe performance cleanup: cache auth.uid() once per statement
-- and remove two confirmed duplicate indexes. No access model is changed.

alter policy "Users manage own PWA push subscriptions" on public.pwa_push_subscriptions using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "client_credits_select_own" on public.client_credits using (user_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid()) limit 1));
alter policy "lawyer achievements own delete" on public.lawyer_achievements using (exists (select 1 from public.lawyer_profiles lp where lp.id = lawyer_achievements.lawyer_id and (lp.profile_id = (select auth.uid()) or exists (select 1 from public.profiles p where p.id = lp.profile_id and p.auth_id = (select auth.uid())))));
alter policy "lawyer achievements own insert" on public.lawyer_achievements with check (exists (select 1 from public.lawyer_profiles lp where lp.id = lawyer_achievements.lawyer_id and (lp.profile_id = (select auth.uid()) or exists (select 1 from public.profiles p where p.id = lp.profile_id and p.auth_id = (select auth.uid())))));
alter policy "lawyer achievements own update" on public.lawyer_achievements using (exists (select 1 from public.lawyer_profiles lp where lp.id = lawyer_achievements.lawyer_id and (lp.profile_id = (select auth.uid()) or exists (select 1 from public.profiles p where p.id = lp.profile_id and p.auth_id = (select auth.uid()))))) with check (exists (select 1 from public.lawyer_profiles lp where lp.id = lawyer_achievements.lawyer_id and (lp.profile_id = (select auth.uid()) or exists (select 1 from public.profiles p where p.id = lp.profile_id and p.auth_id = (select auth.uid())))));
alter policy "lawyer achievements owner delete" on public.lawyer_achievements using ((lawyer_id = (select auth.uid())) or exists (select 1 from public.profiles p where p.id = lawyer_achievements.lawyer_id and p.auth_id = (select auth.uid())));
alter policy "lawyer achievements owner insert" on public.lawyer_achievements with check ((lawyer_id = (select auth.uid())) or exists (select 1 from public.profiles p where p.id = lawyer_achievements.lawyer_id and p.auth_id = (select auth.uid())));
alter policy "lawyer achievements owner update" on public.lawyer_achievements using ((lawyer_id = (select auth.uid())) or exists (select 1 from public.profiles p where p.id = lawyer_achievements.lawyer_id and p.auth_id = (select auth.uid()))) with check ((lawyer_id = (select auth.uid())) or exists (select 1 from public.profiles p where p.id = lawyer_achievements.lawyer_id and p.auth_id = (select auth.uid())));
alter policy "authenticated can create own no show review" on public.no_show_review_requests with check (reporter_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid())));
alter policy "admins can view no show reviews" on public.no_show_review_requests using (exists (select 1 from public.profiles p where p.auth_id = (select auth.uid()) and p.role = 'admin'::user_role));
alter policy "admins can review no show reviews" on public.no_show_review_requests using (exists (select 1 from public.profiles p where p.auth_id = (select auth.uid()) and p.role = 'admin'::user_role)) with check (exists (select 1 from public.profiles p where p.auth_id = (select auth.uid()) and p.role = 'admin'::user_role));
alter policy "financial_ledger_admin" on public.financial_ledger using (exists (select 1 from public.profiles where profiles.auth_id = (select auth.uid()) and profiles.role = 'admin'::user_role));
alter policy "financial_ledger_client_select" on public.financial_ledger using (client_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid())));
alter policy "financial_ledger_lawyer_select" on public.financial_ledger using (lawyer_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid())));
alter policy "payment_financials_admin" on public.payment_financials using (exists (select 1 from public.profiles where profiles.auth_id = (select auth.uid()) and profiles.role = 'admin'::user_role));
alter policy "payment_financials_client_select" on public.payment_financials using (client_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid())));
alter policy "payment_financials_lawyer_select" on public.payment_financials using (lawyer_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid())));
alter policy "lawyer payout self insert" on public.lawyer_payout_requests with check (lawyer_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid())));
alter policy "lawyer_payout_self_read" on public.lawyer_payout_requests using (lawyer_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid())) or exists (select 1 from public.profiles where profiles.auth_id = (select auth.uid()) and profiles.role = 'admin'::user_role));
alter policy "lawyer payout attempts own read" on public.lawyer_payout_attempts using (exists (select 1 from public.lawyer_payout_requests lpr join public.lawyer_profiles lp on lp.id = lpr.lawyer_id join public.profiles p on p.id = lp.profile_id where lpr.id = lawyer_payout_attempts.payout_id and p.id = (select auth.uid())));
alter policy "lawyer wallet self read" on public.lawyer_wallets using (lawyer_id = (select profiles.id from public.profiles where profiles.auth_id = (select auth.uid())));
alter policy "cancellation requests participant read" on public.cancellation_requests using (client_id = (select auth.uid()) or exists (select 1 from public.lawyer_profiles lp join public.profiles p on p.id = lp.profile_id where lp.id = cancellation_requests.lawyer_id and p.id = (select auth.uid())) or is_admin());
alter policy "cancellation requests lawyer create" on public.cancellation_requests with check (exists (select 1 from public.lawyer_profiles lp join public.profiles p on p.id = lp.profile_id where lp.id = cancellation_requests.lawyer_id and p.id = (select auth.uid())));
alter policy "lawyer penalties participant read" on public.lawyer_penalties using (client_id = (select auth.uid()) or exists (select 1 from public.lawyer_profiles lp join public.profiles p on p.id = lp.profile_id where lp.id = lawyer_penalties.lawyer_id and p.id = (select auth.uid())) or is_admin());
alter policy "penalty settlements participant read" on public.lawyer_penalty_settlements using (client_id = (select auth.uid()) or exists (select 1 from public.lawyer_profiles lp join public.profiles p on p.id = lp.profile_id where lp.id = lawyer_penalty_settlements.lawyer_id and p.id = (select auth.uid())) or is_admin());
alter policy "platform_financial_settings_admin" on public.platform_financial_settings using (exists (select 1 from public.profiles where profiles.auth_id = (select auth.uid()) and profiles.role = 'admin'::user_role)) with check (exists (select 1 from public.profiles where profiles.auth_id = (select auth.uid()) and profiles.role = 'admin'::user_role));

drop index if exists public.idx_financial_ledger_lawyer;
drop index if exists public.no_show_review_requests_pending_booking_uidx;
