drop policy if exists conversations_update on public.conversations;
create policy conversations_update on public.conversations for update to authenticated using ((select auth.uid()) = get_profile_auth_id(user_id) or (select auth.uid()) = get_profile_auth_id(lawyer_id)) with check ((select auth.uid()) = get_profile_auth_id(user_id) or (select auth.uid()) = get_profile_auth_id(lawyer_id));
drop policy if exists messages_update on public.messages;
create policy messages_update on public.messages for update to authenticated using ((select auth.uid()) = get_profile_auth_id(sender_id)) with check ((select auth.uid()) = get_profile_auth_id(sender_id));
drop policy if exists notifications_update on public.notifications;
create policy notifications_update on public.notifications for update to authenticated using ((select auth.uid()) = get_profile_auth_id(user_id) or get_my_role() = any(array['admin'::user_role,'moderator'::user_role])) with check ((select auth.uid()) = get_profile_auth_id(user_id) or get_my_role() = any(array['admin'::user_role,'moderator'::user_role]));
drop policy if exists conversations_insert on public.conversations;
create policy conversations_insert on public.conversations for insert to authenticated with check ((select auth.uid()) = get_profile_auth_id(user_id) or (select auth.uid()) = get_profile_auth_id(lawyer_id));
drop policy if exists conversations_select on public.conversations;
create policy conversations_select on public.conversations for select to authenticated using ((select auth.uid()) = get_profile_auth_id(user_id) or (select auth.uid()) = get_profile_auth_id(lawyer_id) or get_my_role() = any(array['admin'::user_role,'moderator'::user_role]));
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated with check ((select auth.uid()) = get_profile_auth_id(sender_id) and exists (select 1 from conversations c where c.id=messages.conversation_id and ((select auth.uid())=get_profile_auth_id(c.user_id) or (select auth.uid())=get_profile_auth_id(c.lawyer_id))));
drop policy if exists messages_select on public.messages;
create policy messages_select on public.messages for select to authenticated using (exists (select 1 from conversations c where c.id=messages.conversation_id and ((select auth.uid())=get_profile_auth_id(c.user_id) or (select auth.uid())=get_profile_auth_id(c.lawyer_id))));
drop policy if exists notifications_delete on public.notifications;
create policy notifications_delete on public.notifications for delete to authenticated using ((select auth.uid()) = get_profile_auth_id(user_id) or get_my_role() = any(array['admin'::user_role,'moderator'::user_role]));
drop policy if exists notifications_select on public.notifications;
create policy notifications_select on public.notifications for select to authenticated using ((select auth.uid()) = get_profile_auth_id(user_id) or get_my_role() = any(array['admin'::user_role,'moderator'::user_role]));
drop policy if exists notifications_insert on public.notifications;
create policy notifications_insert on public.notifications for insert to authenticated with check (get_my_role() = any(array['admin'::user_role,'moderator'::user_role]));
drop policy if exists specialization_requests_delete on public.specialization_change_requests;
create policy specialization_requests_delete on public.specialization_change_requests for delete to authenticated using ((select auth.uid()) = get_profile_auth_id(lawyer_id) or get_my_role() = any(array['admin'::user_role,'moderator'::user_role]));
drop policy if exists specialization_requests_insert on public.specialization_change_requests;
create policy specialization_requests_insert on public.specialization_change_requests for insert to authenticated with check ((select auth.uid()) = get_profile_auth_id(lawyer_id));
drop policy if exists specialization_requests_select on public.specialization_change_requests;
create policy specialization_requests_select on public.specialization_change_requests for select to authenticated using ((select auth.uid()) = get_profile_auth_id(lawyer_id) or get_my_role() = any(array['admin'::user_role,'moderator'::user_role]));
drop policy if exists specialization_requests_update on public.specialization_change_requests;
create policy specialization_requests_update on public.specialization_change_requests for update to authenticated using (get_my_role() = any(array['admin'::user_role,'moderator'::user_role])) with check (get_my_role() = any(array['admin'::user_role,'moderator'::user_role]));
