create or replace function public.create_booking(p_lawyer_id uuid, p_scheduled_at timestamptz, p_package_name text, p_consultation_type text, p_description text default null, p_document_url text default null, p_client_whatsapp text default null, p_slot_id uuid default null)
returns public.bookings language plpgsql security definer set search_path to '' as $function$
declare v_user_id uuid; v_booking public.bookings; v_package jsonb; v_price numeric; v_duration integer:=30; v_description text; v_methods jsonb; v_slot_id uuid; v_slot_starts_at timestamptz; v_is_custom boolean:=lower(trim(coalesce(p_package_name,'')))=lower('استشارة مختلفة');
begin
if auth.uid() is null then raise exception 'يجب تسجيل الدخول أولاً'; end if;
select id into v_user_id from public.profiles where auth_id=auth.uid(); if v_user_id is null then raise exception 'ملف المستخدم غير مكتمل'; end if;
if not exists(select 1 from public.lawyer_profiles where profile_id=p_lawyer_id and verified=true and availability=true) then raise exception 'المحامي غير متاح للحجز حالياً'; end if;
if p_slot_id is not null then select id,starts_at into v_slot_id,v_slot_starts_at from public.lawyer_availability_slots where id=p_slot_id and lawyer_id=p_lawyer_id and is_available=true for update;
else select id,starts_at into v_slot_id,v_slot_starts_at from public.lawyer_availability_slots where lawyer_id=p_lawyer_id and starts_at between p_scheduled_at-interval '60 seconds' and p_scheduled_at+interval '60 seconds' and is_available=true order by abs(extract(epoch from(starts_at-p_scheduled_at))) limit 1 for update; end if;
if v_slot_id is null then raise exception 'عذراً، هذا الموعد لم يعد متاحاً'; end if; if v_slot_starts_at<=now() then raise exception 'الموعد يجب أن يكون في المستقبل'; end if;
if v_is_custom then select consultation_price into v_price from public.lawyer_profiles where profile_id=p_lawyer_id; if v_price is null or v_price<=0 then raise exception 'سعر الاستشارة غير محدد لدى المحامي'; end if;
else select elem into v_package from public.lawyer_profiles lp,lateral jsonb_array_elements(coalesce(lp.services,'[]'::jsonb)) elem where lp.profile_id=p_lawyer_id and lower(coalesce(elem->>'title',''))=lower(trim(p_package_name)) limit 1; if v_package is null then raise exception 'الباقة المحددة غير متاحة'; end if; v_price:=nullif(v_package->>'price','')::numeric; v_duration:=coalesce(nullif(v_package->>'duration_minutes','')::integer,30); v_description:=v_package->>'description'; v_methods:=v_package->'consultation_types'; if v_price is null or v_price<=0 then raise exception 'سعر الباقة غير صالح'; end if; if jsonb_typeof(v_methods)='array' and not(v_methods ? p_consultation_type) then raise exception 'طريقة الاستشارة غير متاحة لهذه الباقة'; end if; if p_consultation_type not in('نصية','صوتية','فيديو') then raise exception 'طريقة الاستشارة غير صالحة'; end if; end if;
if exists(select 1 from public.bookings b where b.lawyer_id=p_lawyer_id and b.scheduled_at between v_slot_starts_at-interval '1 second' and v_slot_starts_at+interval '1 second' and b.status not in('ملغي','مسترد')) then raise exception 'عذراً، هذا الموعد لم يعد متاحاً'; end if;
insert into public.bookings(user_id,lawyer_id,status,scheduled_at,price,consultation_type,description,document_url,whatsapp_number,package_name,package_description,package_duration_minutes,consultation_status,lawyer_approved,lawyer_approved_at) values(v_user_id,p_lawyer_id,'قيد انتظار الدفع',v_slot_starts_at,v_price,trim(p_consultation_type),nullif(trim(p_description),''),p_document_url,nullif(trim(p_client_whatsapp),''),case when v_is_custom then 'استشارة مختلفة' else trim(p_package_name) end,v_description,v_duration,'لم تبدأ',false,null) returning * into v_booking;
update public.lawyer_availability_slots set is_available=false where id=v_slot_id; return v_booking; end; $function$;

create or replace function public.review_booking(p_booking_id uuid,p_approved boolean) returns public.bookings language plpgsql security definer set search_path to 'public' as $function$
declare v_actor uuid:=auth.uid(); v_profile_id uuid; v_booking public.bookings;
begin if v_actor is null then raise exception 'يجب تسجيل الدخول أولاً'; end if; select id into v_profile_id from public.profiles where auth_id=v_actor limit 1; select * into v_booking from public.bookings where id=p_booking_id for update; if not found then raise exception 'الحجز غير موجود'; end if; if v_booking.lawyer_id<>v_profile_id then raise exception 'غير مصرح بهذا الإجراء'; end if; if v_booking.status not in('قيد انتظار الدفع','قيد معالجة الدفع') or v_booking.lawyer_approved then raise exception 'لا يمكن مراجعة هذا الطلب في حالته الحالية'; end if; update public.bookings set lawyer_approved=p_approved,lawyer_approved_at=case when p_approved then now() else null end,status=case when p_approved then status else 'ملغي' end,cancelled_at=case when not p_approved then now() else null end where id=p_booking_id returning * into v_booking; return v_booking; end; $function$;

create or replace function public.change_booking_status(p_booking_id uuid,p_new_status text) returns public.bookings language plpgsql security definer set search_path to 'public' as $function$
declare v_actor uuid:=auth.uid(); v_profile_id uuid; v_booking public.bookings; v_is_admin boolean:=public.is_admin(); v_is_paid boolean;
begin if v_actor is null then raise exception 'يجب تسجيل الدخول أولاً'; end if; if p_new_status not in('مؤكد','قيد التنفيذ','مكتمل','ملغي','مسترد') then raise exception 'حالة الحجز غير صالحة'; end if; select id into v_profile_id from public.profiles where auth_id=v_actor limit 1; select * into v_booking from public.bookings where id=p_booking_id for update; if not found then raise exception 'الحجز غير موجود'; end if; select exists(select 1 from public.payments where booking_id=v_booking.id and status='تم الدفع') into v_is_paid; if v_is_admin then null; elsif v_booking.user_id=v_profile_id and p_new_status='ملغي' and v_booking.status in('قيد انتظار الدفع','قيد معالجة الدفع','مؤكد') then null; elsif v_booking.lawyer_id=v_profile_id and p_new_status='قيد التنفيذ' then if v_booking.status<>'مؤكد' or not v_is_paid or not v_booking.lawyer_approved or v_booking.consultation_status<>'لم تبدأ' then raise exception 'لا يمكن بدء الاستشارة قبل تأكيد الدفع والحجز وموافقة المحامي'; end if; elsif v_booking.lawyer_id=v_profile_id and p_new_status='مكتمل' then if v_booking.status<>'قيد التنفيذ' or v_booking.consultation_status<>'قيد التنفيذ' then raise exception 'لا يمكن إنهاء الاستشارة في حالتها الحالية'; end if; elsif v_booking.lawyer_id=v_profile_id and p_new_status='ملغي' and v_booking.status in('قيد انتظار الدفع','قيد معالجة الدفع','مؤكد','قيد التنفيذ') then null; else raise exception 'غير مصرح بهذا الإجراء'; end if; update public.bookings set status=p_new_status,consultation_status=case when p_new_status='قيد التنفيذ' then 'قيد التنفيذ' when p_new_status='مكتمل' then 'انتهت' when p_new_status='ملغي' and status='قيد التنفيذ' then 'أُلغيت' else consultation_status end,completed_at=case when p_new_status='مكتمل' then now() else completed_at end,cancelled_at=case when p_new_status='ملغي' then now() else cancelled_at end where id=p_booking_id returning * into v_booking; return v_booking; end; $function$;

create or replace function public.sync_booking_from_payment() returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare v_booking public.bookings%rowtype; v_verifier uuid;
begin select * into v_booking from public.bookings where id=new.booking_id for update; if not found then raise exception 'الحجز غير موجود'; end if; select id into v_verifier from public.profiles where auth_id=auth.uid(); if new.status='تم الدفع' then if v_booking.status<>'قيد معالجة الدفع' then raise exception 'لا يمكن اعتماد الدفع في حالة الحجز الحالية'; end if; if not v_booking.lawyer_approved then raise exception 'لا يمكن اعتماد الدفع قبل موافقة المحامي'; end if; new.verified_by:=v_verifier; new.verified_at:=now(); update public.bookings set status='مؤكد' where id=new.booking_id; elsif new.status='فشل الدفع' then if v_booking.status<>'قيد معالجة الدفع' then raise exception 'لا يمكن رفض الدفع في حالة الحجز الحالية'; end if; new.verified_by:=v_verifier; new.verified_at:=now(); update public.bookings set status='قيد انتظار الدفع' where id=new.booking_id; elsif new.status='تم استرداد المبلغ' then if v_booking.status not in('مؤكد','قيد التنفيذ','مكتمل') then raise exception 'لا يمكن استرداد هذا الحجز في حالته الحالية'; end if; new.verified_by:=v_verifier; new.verified_at:=now(); update public.bookings set status='مسترد' where id=new.booking_id; end if; return new; end; $function$;
